Remove /Zm option in Visual Studio.
Attempt to fix "error C1060: compiler is out of heap space".
Apparently /Zm can cause this - and not needed since VS2015.